// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLU0QnT2ypS7r9x3zM61pG-5uOxtVkTpo',
    appId: '1:50672581976:web:689b5275ab7202c8f4392d',
    messagingSenderId: '50672581976',
    projectId: 'summer-2024-r2-1c8c8',
    authDomain: 'summer-2024-r2-1c8c8.firebaseapp.com',
    storageBucket: 'summer-2024-r2-1c8c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGbepp1jZcNpyn1YGkNIabRMHc-3tgQhU',
    appId: '1:50672581976:android:b6eed975ccb1c5b0f4392d',
    messagingSenderId: '50672581976',
    projectId: 'summer-2024-r2-1c8c8',
    storageBucket: 'summer-2024-r2-1c8c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0fw94m0-_Mb2TS1z7fgn2Lrx9VeXPfU',
    appId: '1:50672581976:ios:d1e86b6e3ae3ce4df4392d',
    messagingSenderId: '50672581976',
    projectId: 'summer-2024-r2-1c8c8',
    storageBucket: 'summer-2024-r2-1c8c8.appspot.com',
    iosBundleId: 'com.example.firebaseSession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0fw94m0-_Mb2TS1z7fgn2Lrx9VeXPfU',
    appId: '1:50672581976:ios:d1e86b6e3ae3ce4df4392d',
    messagingSenderId: '50672581976',
    projectId: 'summer-2024-r2-1c8c8',
    storageBucket: 'summer-2024-r2-1c8c8.appspot.com',
    iosBundleId: 'com.example.firebaseSession',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLU0QnT2ypS7r9x3zM61pG-5uOxtVkTpo',
    appId: '1:50672581976:web:84310dcda87e13e7f4392d',
    messagingSenderId: '50672581976',
    projectId: 'summer-2024-r2-1c8c8',
    authDomain: 'summer-2024-r2-1c8c8.firebaseapp.com',
    storageBucket: 'summer-2024-r2-1c8c8.appspot.com',
  );
}
